name = "Pres"
uuid = "ad8279e5-616a-41b2-a10c-ecf76fd8a6a4"
authors = ["BENCHEIKH El Amira Cerine <bencheikhelamiracerine@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
